title: 宇宙物理メモ
description: An astrophysics and physics memo.
twitter_username: tweetnakasho
github_username:  github-nakasho
ga_tracking: G-C550SVR5KQ
ga_tracking_anonymize_ip: true
theme: "just-the-docs"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-diagrams
  - jekyll-pdf-embed
souce: ./mds
destination: ./docs
domain: github-nakasho.github.io
url: https://github-nakasho.github.io
logo: /assets/images/logo.png
thumbnail: /assets/images/logo.png
heading_anchors: true
footer_content: "Copyright &copy; github-nakasho"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
color_scheme: for_astrophysics
gems:
  - jekyll-amazon
