title: 宇宙物理メモ
description: An astrophysics and physics memo.
twitter_username: tweet_nakasho
github_username:  github-nakasho
ga_tracking: G-C550SVR5KQ
ga_tracking_anonymize_ip: true
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
souce: ./mds
destination: ./docs
domain: github-nakasho.github.io
url: https://github-nakasho.github.io
logo: /assets/images/logo.png
