title: 宇宙物理メモ
description: An astrophysics and physics memo.
twitter_username: tweet_nakasho
github_username:  github-nakasho
google_analytics: G-C550SVR5KQ
theme: "just-the-docs"
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin

