title: 宇宙物理メモ
description: An astrophysics and physics memo.
twitter_username: tweet_nakasho
github_username:  github-nakasho
google_analytics: G-C550SVR5KQ
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
souce: ./mds
destination: ./docs
domain: github-nakasho.github.io
url: https://github-nakasho.github.io

